import { marked } from "marked"
import { PaperMeta } from "../apis/zotero/item"
import { ReviewPayload } from "../llm/schema"
import { overallScore } from "./review-md"

function esc(s: string): string {
  return (s || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

function md(s: string): string {
  try {
    return marked.parse(s || "", { async: false }) as string
  } catch {
    return esc(s)
  }
}

const CSS = `
:root{--accent:#2b6cb0;--bg:#f7fafc;--card:#fff;--border:#e2e8f0;--text:#1a202c;--muted:#718096}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--text);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Apple SD Gothic Neo","Malgun Gothic",sans-serif;line-height:1.7}
main{max-width:820px;margin:0 auto;padding:40px 24px 80px}
h1{font-size:1.7rem;line-height:1.35;margin:0 0 12px}
h2{font-size:1.15rem;margin:32px 0 10px;padding-bottom:6px;border-bottom:2px solid var(--accent);color:var(--accent)}
.meta{color:var(--muted);font-size:.9rem;margin-bottom:20px}
.meta a{color:var(--accent);text-decoration:none}
.essence{background:var(--card);border:1px solid var(--border);border-left:4px solid var(--accent);border-radius:8px;padding:16px 20px;margin:16px 0;font-size:1.02rem}
.scores{display:flex;gap:10px;flex-wrap:wrap;margin:16px 0}
.badge{background:var(--card);border:1px solid var(--border);border-radius:999px;padding:6px 14px;font-size:.85rem}
.badge b{color:var(--accent)}
.overall{background:var(--accent);color:#fff;border-color:var(--accent)}
.overall b{color:#fff}
table{border-collapse:collapse;width:100%;margin:12px 0}
th,td{border:1px solid var(--border);padding:8px 12px;text-align:left}
th{background:var(--bg)}
blockquote{border-left:3px solid var(--accent);margin:12px 0;padding:6px 16px;color:var(--muted);background:var(--card)}
ul{padding-left:22px}
.footer{margin-top:48px;padding-top:16px;border-top:1px solid var(--border);color:var(--muted);font-size:.8rem}
`

export function renderIndexHtml(
  meta: PaperMeta,
  payload: ReviewPayload,
  opts: { provider: string; reviewDate: string },
): string {
  const overall = overallScore(payload)
  const authors = meta.authors.join(", ") || "(미상)"
  const urlHtml = meta.url
    ? `<a href="${esc(meta.url)}">${esc(meta.url)}</a>`
    : "(없음)"

  const badge = (label: string, v: number, cls = "") =>
    `<span class="badge ${cls}">${label} <b>${v.toFixed(1)}</b></span>`

  return `<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(meta.title)}</title>
<style>${CSS}</style>
</head>
<body>
<main>
  <h1>${esc(meta.title)}</h1>
  <div class="meta">${esc(authors)} &nbsp;|&nbsp; ${esc(meta.date || "(미상)")} &nbsp;|&nbsp; ${urlHtml}</div>

  <div class="essence">${md(payload.essence)}</div>

  <div class="scores">
    ${badge("Novelty", payload.novelty)}
    ${badge("Technical", payload.technical)}
    ${badge("Significance", payload.significance)}
    ${badge("Clarity", payload.clarity)}
    ${badge("Overall", overall, "overall")}
  </div>

  <h2>Motivation</h2>
  <ul>
    <li><b>Known</b>: ${md(payload.known)}</li>
    <li><b>Gap</b>: ${md(payload.gap)}</li>
    <li><b>Why</b>: ${md(payload.why)}</li>
    <li><b>Approach</b>: ${md(payload.approach)}</li>
  </ul>

  <h2>Achievement</h2>
  ${md(payload.achievement)}

  <h2>How</h2>
  ${md(payload.how)}

  <h2>Originality</h2>
  ${md(payload.originality)}

  <h2>Limitation</h2>
  ${md(payload.limitation)}

  <h2>Evaluation</h2>
  <blockquote>${esc(payload.verdict)}</blockquote>

  <div class="footer">
    Generated by Paper Curio · ${esc(opts.provider)} · ${esc(opts.reviewDate)} ·
    분류(category)는 paper-curation 빌드 시 자동 부여됩니다.
  </div>
</main>
</body>
</html>`
}
